name: Publish VSIX

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build VSIX package
        run: npx @vscode/vsce package --no-dependencies

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: extension-vsix
          path: '*.vsix'

      - name: Upload VSIX to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          files: '*.vsix'
